package com.project.Render;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

import com.project.BoardController.Location;
import com.project.Main.GameType;
import com.project.Main.Main;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;


// Board object, has all the information about the frame 

// PLEASE DO NOT EDIT THIS FILE. IF YOU NEED TO, PLEASE BE CAREFUL!

public class Board {

	private JFrame frmChess;

	public Board() {
		initialize();
		frmChess.setVisible(true);
	}

	// Information:
	// 
	
	// Auto render piece sizes to bounds: x, y, 60, 60
	private void initialize() {
		CenterPointManager point = new CenterPointManager();
		
		JLabel lblNewLabel = new JLabel("");
		
		lblNewLabel.setIcon(new ImageIcon(getClass().getResource("standard-walnut-chess-board-21184254145_1024x1024.jpg")));
		lblNewLabel.setBounds(0, 0, 716, 723);
		
		frmChess = new JFrame();
		
		frmChess.setContentPane(lblNewLabel);
		
		frmChess.setResizable(false);
		frmChess.setTitle("Chess");
		frmChess.setBounds(100, 100, 706, 755);
		frmChess.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frmChess.getContentPane().setLayout(null);
		
		JMenuBar menuBar = new JMenuBar();
		frmChess.setJMenuBar(menuBar);
		
		JMenu mnNewMenu = new JMenu("Game Manager");
		menuBar.add(mnNewMenu);
		
		JMenuItem playerVPlayerGame = new JMenuItem("Play Player vs Player Game");
		playerVPlayerGame.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Main.createNewGame(GameType.PLAYER_VS_PLAYER);
			}
		});
		mnNewMenu.add(playerVPlayerGame);
		
		JMenuItem playerVAIGame = new JMenuItem("Play Player vs AI Game");
		playerVAIGame.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Main.createNewGame(GameType.PLAYER_VS_AI);
			}
		});
		mnNewMenu.add(playerVAIGame);
		
		JMenuItem AI_V_AI_Game = new JMenuItem("Play AI vs AI Game");
		AI_V_AI_Game.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Main.createNewGame(GameType.PLAYER_VS_AI);
			}
		});
		mnNewMenu.add(AI_V_AI_Game);
	}
	
	public JFrame getFrame() {
		return frmChess;
	}
}
